openapi: 3.0.3
info:
  title: Book Management System API
  version: 0.0.0
  description: capstone project for Slightly Techie School
paths:
  /books/:
    get:
      operationId: books_retrieve
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /books/books-create/:
    post:
      operationId: books_books_create_create
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /books/books-delete/{id}/:
    delete:
      operationId: books_books_delete_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /books/books-detail/{id}/:
    get:
      operationId: books_books_detail_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /books/books-list/:
    get:
      operationId: books_books_list_retrieve
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /books/books-update/{id}/:
    post:
      operationId: books_books_update_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
